# https://docs.codacy.com/repositories-configure/codacy-configuration-file/

exclude_paths:
  - "assets/**/*"
  - "database/**/*"
  - "models/**/*"
  - "postman_collections/**/*"
  - "schemas/**/*"
  - "tests/**/*"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.txt"
  - "**/__pycache__/"
  - "**/*.pyc"
  - "LICENSE"
  - "main.py"
  - "README.md"
