services:
  api:
    image: python-samples-fastapi-restful
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - storage:/storage/
    environment:
      - PYTHONUNBUFFERED=1
      - STORAGE_PATH=/storage/players-sqlite3.db
    restart: unless-stopped

volumes:
  storage:
    name: python-samples-fastapi-restful_storage
